print("AREA DEL PARALELOGRAMO")
b=float(input("BASE:   "))
h=float(input("ALTURA: "))
A=int(b*h)
print("AREA: ",A,"cm2")
print("")
print("PERIMETRO DEL PARALELOGRAMO")
p=int((2*h)+(2*b))
print ("PERIMETRO: ",p,"cm")