print("AREA DEL ROMBO")
D=float(input("DIAMETRO MAYOR: "))
dd=float(input("DIAMETRO MENOR: "))
A=int((D*dd)/2)
print(f"AREA: ",A,"cm")
print("")
print("PERIMTRO DEL ROMBO")
l=float(input("LADO: "))
P=int(4*l)
print("PERIMETRO: ",P,"cm")