print("AREA DEL RECTANGULO")
b=float(input("BASE:   "))
h=float(input("ALTURA: "))
A=int(b*h)
print("AREA: ",A,"cm")
print("")
print("PERIMETRO RECTANGULO")
p=int((2*h)+(2*b))
print ("PERIMETRO: ",p,"cm")